#!/bin/sh
# /etc/init.d/flashpolicyd
# Written by Martin Eisenbarth <eyesee@foobarlab.net>
### BEGIN INIT INFO
# Provides:          flashpolicyd
# Required-Start:    networking
# Required-Stop:     networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Flashpolicy daemon
# Description:       A standalone flashpolicyd to serve crossdomain.xml requests
### END INIT INFO

PORT=843	# default crossdomain policy port, set to unpriviledged port (>1024) if you encounter firewall issues
DAEMON=/usr/local/bin/flashpolicyd.py
POLICY=/usr/local/etc/crossdomain.xml
LOGFILE=/var/log/policyd.log
NAME=policyd
DESC="serve crossdomain requests"

DAEMON_OPTS="--port $PORT --file $POLICY"

PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
SSD="/sbin/start-stop-daemon"

test -x $DAEMON || exit 1

set -e

 . /lib/lsb/init-functions


case "$1" in
  start)
        log_daemon_msg "Starting $DESC" $NAME
        if ! $SSD --start --quiet --pidfile $PIDFILE --make-pidfile --background --exec $DAEMON -- $DAEMON_OPTS ; then
            log_end_msg 1
        else
            log_end_msg 0
        fi
    ;;
  stop)
        log_daemon_msg "Stopping $DESC" $NAME
        if $SSD --stop --retry 30 --pidfile $PIDFILE ; then
            rm -f $PIDFILE
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;
  restart|force-reload)
        $0 stop
        [ -r  $PIDFILE ] && while pidof -x $NAME | grep -q `cat $PIDFILE 2>/dev/null` 2>/dev/null ; do sleep 1; done
        $0 start
        ;;
  *)
        echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
