#! /bin/sh
# /etc/init.d/upstage
# Written by Martin Eisenbarth <eyesee@foobarlab.net>
### BEGIN INIT INFO
# Provides:          upstage
# Required-Start:    networking
# Required-Stop:     networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: UpStage Server
# Description:       UpStage is a platform for cyberformance.
### END INIT INFO

start() {
    echo "Starting UpStage ..."
    su -l upstage -c "/opt/upstage/upstage start &"
}

stop() {
    echo "Stopping UpStage ..."
    su -l upstage -c "/opt/upstage/upstage stop &"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    *)
        echo "Usage: upstage {start|stop}"
        exit 1

esac

exit 0

