		</div>
		<div id="footer">
			<!-- TODO dynamically insert version number -->
			<p style="font-size:9px;font-weight:bold;color:#bbb;font-family:Verdana,Arial,'Bitstream Vera Sans',Helvetica,sans-serif">UpStage version 3.0.0.foobarlab.1 (patched v3-beta version) &mdash; <a href="https://github.com/foobarlab/UpStage-v3-beta-with-patches" style="color:#bbb;text-decoration:none"><i class="icon-github-alt icon-large"></i> Fork me on GitHub</a> &mdash; <a href="https://github.com/foobarlab/UpStage-v3-beta-with-patches/issues" style="color:#bbb;text-decoration:none">Report a bug</a></p>
		</div>
		<div id="status" style="display:none;">
		</div>
	</div>
</body>
</html>
